### ISSUE TITLE
Hello, does version 0.5.3 support account password login? My remote server does not set up the cert login method.

### ISSUE THREAD

**Issue by MRDHR** [oxfs/oxfs#18]
Hello, does version 0.5.3 support account password login? My remote server does not set up the cert login method.

**Comment by RainMark** [comment]
yes, you can use pip to  install 0.5.4 directly

**Comment by MRDHR** [comment]
I have tried to use the-- password and-- passwd parameters, both of which indicate that the parameters are invalid
![image](https://user-images.githubusercontent.com/5576916/236593706-80816efc-d607-4a9f-b1fa-0442eafb164b.png)

I have also checked the submission record of git, and after version 0.5.1, you added the way to log in through the cert file, when the parameter of password was deleted.
![image](https://user-images.githubusercontent.com/5576916/236593824-9400d05e-21f2-478f-ac17-4fd824ebacf6.png)

**Comment by MRDHR** [comment]
I tried to specify the version 0.5.0 and 0.5.1 installed. After installation, the cache directory does not exist in the directory of dist-packages/oxfs, which makes the old version unusable.

**Comment by MRDHR** [comment]
算了 还是用中文回复吧。翻译机翻译的都不知道对不对的
试过装0.4.0，0.5.0，0.5.1这三个版本， dist-packages/oxfs这个目录下的cache目录不存在，在执行oxfs挂载命令的时候提示cache模块不存在。

**Comment by MRDHR** [comment]
![image](https://user-images.githubusercontent.com/5576916/236594110-48c8b905-0c5d-476a-a3ff-5ee2df6f395f.png)
github的提交日志看到去年10月13号的时候 把password的入参给干掉了

**Comment by RainMark** [comment]
不用指定参数，如果没有cert配置会自动fallback让你输入密码

**Comment by MRDHR** [comment]
但是并没有呢，提示paramiko.ssh_exception.SSHException: No authentication methods available
![image](https://user-images.githubusercontent.com/5576916/236594453-1374da7b-e2c2-494d-869a-c49659dd92ab.png)

**Comment by RainMark** [comment]
https://github.com/oxfs/oxfs/blob/cf6176de690461ab401db0b445657714d84d45bc/oxfs/oxfs.py#L104-L107

这样，你打开本地代码把这几行注释了，看样子是paramiko抛了个SSHException没catch住

**Comment by RainMark** [comment]
https://github.com/oxfs/oxfs/blob/cf6176de690461ab401db0b445657714d84d45bc/setup.py#L35

估计是paramiko新版本行为发生了改变，也可以试试pip install paramiko==2.0.0试试

**Comment by MRDHR** [comment]
![image](https://user-images.githubusercontent.com/5576916/236594934-a566bbe6-c2f7-44b0-bbe8-dcd9fcc6db5c.png)
安装了2.0.0版本，出现符号错误

**Comment by RainMark** [comment]
奇怪了，试试2.8.0呢，我看3.0是最近才发布的，2.0.0有点旧了

**Comment by MRDHR** [comment]
![image](https://user-images.githubusercontent.com/5576916/236595153-87c819b3-45bf-4bb9-971b-2cc10120a18e.png)
2.8.0版本和之前3.0.0的一样，还是提示paramiko.ssh_exception.SSHException: No authentication methods available

**Comment by RainMark** [comment]
你先本地改下代码吧，我找下正确的版本，代码路径文件你的报错截图里给出了

**Comment by MRDHR** [comment]
可以直接修改dist下的文件？
![05B6ED56](https://user-images.githubusercontent.com/5576916/236595802-00dbac37-2a33-4828-a23f-9e98fcd2ca27.png)

**Comment by RainMark** [comment]
> 可以直接修改dist下的文件？ ![05B6ED56](https://user-images.githubusercontent.com/5576916/236595802-00dbac37-2a33-4828-a23f-9e98fcd2ca27.png)

是的，只要有权限随便改

**Comment by MRDHR** [comment]
注释掉那几行代码后成功了

**Comment by RainMark** [comment]
好，感谢，我稍后修复了重新发个版本

**Comment by MRDHR** [comment]
感谢大佬，我先用用看。

**Comment by RainMark** [comment]
oxfs==0.5.5可以了，可以试试
